CREATE TABLE DWS.RISK_LIC_CARD_APPL(
     DW_ETL_DATE             VARCHAR2(8)            -- 跑批日期
    ,CASE_ID                 NUMBER(32)             -- 案件ID
    ,CREATE_TIME             DATE                   -- 进件时间
    ,CUST_NAME               VARCHAR2(100)          -- 客户名称
    ,AGE                     VARCHAR2(8)            -- 年龄
    ,GENDER                  VARCHAR2(8)            -- 性别
    ,CENSUSADD               VARCHAR2(200)          -- 户籍地址
    ,FACE_RECOGN_SC          VARCHAR2(4)            -- 人脸识别分数
    ,MARITALSTATUS           VARCHAR2(8)            -- 婚否
    ,COMPANY                 VARCHAR2(100)          -- 单位名称
    ,COMPANYADD              VARCHAR2(200)          -- 单位地址
    ,DEPT                    VARCHAR2(100)          -- 部门
    ,POST                    VARCHAR2(100)          -- 岗位
    ,CAREER_TYPE             VARCHAR2(64)           -- 职业类型
    ,SALARY_PRE_TAX          VARCHAR2(30)           -- 税前月收入
    ,EDU                     VARCHAR2(100)          -- 学历
    ,SAME_APPL               VARCHAR2(64)           -- 同申标识
    ,PRODUCT_NAME            VARCHAR2(100)          -- 产品
    ,APPL_CARD_RATE          NUMBER(10,3)           -- 申请费率
    ,APPL_LOAN_PURPOS        VARCHAR2(200)          -- 借款用途
    ,NODE_CODE               VARCHAR2(20)           -- 节点
    ,CASE_STATUS             VARCHAR2(20)           -- 案件状态
    ,CASE_PRIORITY           VARCHAR2(20)           -- 案件优先级
    ,UPDATE_TIME             DATE                   -- 结束时间
    ,AUDIT_RESULT            VARCHAR2(64)           -- 审批结果
    ,AUDIT_CODE1             VARCHAR2(16)           -- 审批代码
    ,AUDIT_ADVICE            VARCHAR2(4000)         -- 意见
    ,TRACK_CODE1             VARCHAR2(16)           -- 跟踪代码1
    ,EXCEPTION_AUDIT_CODE1   VARCHAR2(16)           -- 例批代码1
    ,REFUND_CODE1            VARCHAR2(16)           -- 退件代码1
    ,CUST_GROUP1             VARCHAR2(16)           -- 客群1
    ,CUST_GROUP2             VARCHAR2(16)           -- 客群2
    ,AUDIT_RATE              NUMBER(10,3)           -- 审批费率
    ,AUDIT_QUOTA             NUMBER(12,2)           -- 审批额度
    ,AUDIT_TIME              DATE                   -- 审批时间
    ,RH_EDUCATION            VARCHAR2(100)          -- 学历
    ,RH_HOUSE_LOAN           VARCHAR2(100)          -- 房产贷款
    ,RH_ALL_BALANCE          VARCHAR2(100)          -- 所有负债
    ,RH_CARD_BALANCE         VARCHAR2(100)          -- 所有卡负债
    ,RH_SCORE                VARCHAR2(100)          -- 人行分数
    ,RH_QUERY_1              VARCHAR2(100)          -- 人行近1个月查询次数
    ,RH_QUERY_3              VARCHAR2(100)          -- 人行近3个月查询次数
    ,CZ1_OPERATOR            VARCHAR2(100)          -- 查证经办人
    ,CZ1_BEG_TIME            DATE                   -- 查证开始时间
    ,CZ1_END_TIME            DATE                   -- 查证结束时间
    ,SX1_OPERATOR            VARCHAR2(100)          -- 授信1经办人
    ,SX1_BEG_TIME            DATE                   -- 授信1开始时间
    ,SX1_END_TIME            DATE                   -- 授信1开始时间
    ,SX2_OPERATOR            VARCHAR2(100)          -- 授信2经办人
    ,SX2_BEG_TIME            DATE                   -- 授信2开始时间
    ,SX2_END_TIME            DATE                   -- 授信2开始时间
    ,RGFH_OPERATOR           VARCHAR2(100)          -- 人工复核经办人
    ,RGFH_BEG_TIME           DATE                   -- 人工复核开始时间
    ,RGFH_END_TIME           DATE                   -- 人工复核开始时间
    ,BJ_OPERATOR             VARCHAR2(100)          -- 补件经办人
    ,BJ_BEG_TIME             DATE                   -- 补件开始时间
    ,BJ_END_TIME             DATE                   -- 补件开始时间
    ,BAR_CODE                VARCHAR2(16)           -- 申请件号码
    ,PROJECT_CODE            VARCHAR2(16)           -- 项目代码
    ,SOURCE                  VARCHAR2(20)           -- 进件渠道
    ,CZ_CUST_GROUP           VARCHAR2(20)           -- 查证客群
    ,ADVISE_LIMIT            VARCHAR2(30)           -- 策略输出建议额度
    ,ADVISE_CARD_LIMIT       VARCHAR2(30)           -- 信用卡建议额度
    ,DTI                     VARCHAR2(50)           -- 负债收入比
    ,INCOME                  VARCHAR2(20)	          -- 税前收入
    ,DEPOSIT_BASE            NUMBER(12,2)           -- 缴存基数
    ,SALARY_IN_OUT_AVG       NUMBER(12,2)           -- 流水平均值
    ,VISIT_ADDR              VARCHAR2(480)          -- 亲访地址
    ,AM1_NO                  VARCHAR2(32)           -- 客户经理1工号
    ,AM1_NAME                VARCHAR2(100)          -- 客户经理1姓名
    ,AM1_SUB_BRANCH_NAME     VARCHAR2(100)          -- 客户经理1所属支行名称
    ,AM2_NO                  VARCHAR2(32)           -- 客户经理2工号
    ,AM2_NAME                VARCHAR2(100)          -- 客户经理2姓名
    ,AM2_SUB_BRANCH_NAME     VARCHAR2(100)          -- 客户经理2所属支行名称
);

CREATE TABLE DWS.RISK_LIC_LOAN_APPL(
                                       DW_ETL_DATE             VARCHAR2(8)            -- 跑批日期
    ,CASE_ID                 NUMBER(32)             -- 案件ID
    ,CREATE_TIME             DATE                   -- 进件时间
    ,CUST_NAME               VARCHAR2(100)          -- 客户名称
    ,AGE                     VARCHAR2(8)            -- 年龄
    ,GENDER                  VARCHAR2(8)            -- 性别
    ,CENSUSADD               VARCHAR2(200)          -- 户籍地址
    ,FACE_RECOGN_SC          VARCHAR2(4)            -- 人脸识别分数
    ,MARITALSTATUS           VARCHAR2(8)            -- 婚否
    ,COMPANY                 VARCHAR2(100)          -- 单位名称
    ,COMPANYADD              VARCHAR2(200)          -- 单位地址
    ,DEPT                    VARCHAR2(100)          -- 部门
    ,POST                    VARCHAR2(100)          -- 岗位
    ,CAREER_TYPE             VARCHAR2(64)           -- 职业类型
    ,SALARY_PRE_TAX          VARCHAR2(30)           -- 税前月收入
    ,EDU                     VARCHAR2(100)          -- 学历
    ,SAME_APPL               VARCHAR2(64)           -- 同申标识
    ,PRODUCT_NAME            VARCHAR2(100)          -- 产品
    ,APPL_PAY_TYPE           VARCHAR2(16)           -- 申请还款类型
    ,APPL_LOAN_AMT           VARCHAR2(20)           -- 申请借款金额
    ,APPL_LOAN_PERIODS       VARCHAR2(4)            -- 贷款期限
    ,APPL_LOAN_RATE          NUMBER(10,3)           -- 申请费率
    ,APPL_LOAN_PURPOS        VARCHAR2(200)          -- 借款用途
    ,NODE_CODE               VARCHAR2(20)           -- 节点
    ,CASE_STATUS             VARCHAR2(20)           -- 案件状态
    ,CASE_PRIORITY           VARCHAR2(20)           -- 案件优先级
    ,UPDATE_TIME             DATE                   -- 结束时间
    ,AUDIT_RESULT            VARCHAR2(64)           -- 审批结果
    ,AUDIT_CODE1             VARCHAR2(16)           -- 审批代码
    ,AUDIT_ADVICE            VARCHAR2(4000)         -- 意见
    ,AUDIT_LOAN_PERIODS      NUMBER(11)             -- 分期期数
    ,TRACK_CODE1             VARCHAR2(16)           -- 跟踪代码1
    ,EXCEPTION_AUDIT_CODE1   VARCHAR2(16)           -- 例批代码1
    ,REFUND_CODE1            VARCHAR2(16)           -- 退件代码1
    ,CUST_GROUP1             VARCHAR2(16)           -- 客群1
    ,CUST_GROUP2             VARCHAR2(16)           -- 客群2
    ,AUDIT_PAY_TYPE          VARCHAR2(16)           -- 还款方式
    ,AUDIT_RATE              NUMBER(10,3)           -- 审批费率
    ,AUDIT_QUOTA             NUMBER(12,2)           -- 审批额度
    ,AUDIT_TIME              DATE                   -- 审批时间
    ,RH_EDUCATION            VARCHAR2(100)          -- 学历
    ,RH_HOUSE_LOAN           VARCHAR2(100)          -- 房产贷款
    ,RH_ALL_BALANCE          VARCHAR2(100)          -- 所有负债
    ,RH_CARD_BALANCE         VARCHAR2(100)          -- 所有卡负债
    ,RH_SCORE                VARCHAR2(100)          -- 人行分数
    ,RH_QUERY_1              VARCHAR2(100)          -- 人行近1个月查询次数
    ,RH_QUERY_3              VARCHAR2(100)          -- 人行近3个月查询次数
    ,CZ1_OPERATOR            VARCHAR2(100)          -- 查证经办人
    ,CZ1_BEG_TIME            DATE                   -- 查证开始时间
    ,CZ1_END_TIME            DATE                   -- 查证结束时间
    ,SX1_OPERATOR            VARCHAR2(100)          -- 授信1经办人
    ,SX1_BEG_TIME            DATE                   -- 授信1开始时间
    ,SX1_END_TIME            DATE                   -- 授信1开始时间
    ,SX2_OPERATOR            VARCHAR2(100)          -- 授信2经办人
    ,SX2_BEG_TIME            DATE                   -- 授信2开始时间
    ,SX2_END_TIME            DATE                   -- 授信2开始时间
    ,RGFH_OPERATOR           VARCHAR2(100)          -- 人工复核经办人
    ,RGFH_BEG_TIME           DATE                   -- 人工复核开始时间
    ,RGFH_END_TIME           DATE                   -- 人工复核开始时间
    ,BJ_OPERATOR             VARCHAR2(100)          -- 补件经办人
    ,BJ_BEG_TIME             DATE                   -- 补件开始时间
    ,BJ_END_TIME             DATE                   -- 补件开始时间
    ,BAR_CODE                VARCHAR2(16)           -- 申请件号码
    ,PROJECT_CODE            VARCHAR2(16)           -- 项目代码
    ,SOURCE                  VARCHAR2(20)           -- 进件渠道
    ,CZ_CUST_GROUP           VARCHAR2(20)           -- 查证客群
    ,ADVISE_LIMIT            VARCHAR2(30)           -- 策略输出建议额度
    ,ADVISE_CARD_LIMIT       VARCHAR2(30)           -- 信用卡建议额度
    ,DTI                     VARCHAR2(50)           -- 负债收入比
    ,INCOME                  VARCHAR2(20)	          -- 税前收入
    ,DEPOSIT_BASE            NUMBER(12,2)           -- 缴存基数
    ,SALARY_IN_OUT_AVG       NUMBER(12,2)           -- 流水平均值
    ,VISIT_ADDR              VARCHAR2(480)          -- 亲访地址
    ,AM1_NO                  VARCHAR2(32)           -- 客户经理1工号
    ,AM1_NAME                VARCHAR2(100)          -- 客户经理1姓名
    ,AM1_SUB_BRANCH_NAME     VARCHAR2(100)          -- 客户经理1所属支行名称
    ,AM2_NO                  VARCHAR2(32)           -- 客户经理2工号
    ,AM2_NAME                VARCHAR2(100)          -- 客户经理2姓名
    ,AM2_SUB_BRANCH_NAME     VARCHAR2(100)          -- 客户经理2所属支行名称
);